### ISSUE TITLE
老铁东西搞的不耐

### ISSUE THREAD

**Issue by jeruik** [pujiaxin33/JXScratchView#1]
图片用啥软件做呢

**Comment by pujiaxin33** [comment]
你是说美女图片那个吗？图片是从“撕掉她的衣服”安装包里面，解压之后拿出来的。

**Comment by jeruik** [comment]
我是说这个做一张有衣服和没衣服的图片，用啥软件做的，

**Comment by pujiaxin33** [comment]
大哥，这个是摄影师拍摄出来的。让女模特保持位置不动，拍一张正常的，再拍一张暴露的

**Comment by jeruik** [comment]
😁，要是有软件做就更棒了
